amcl:
  ros__parameters:
    use_sim_time: false
    min_particles: 500
    max_particles: 2000
    laser_model_type: likelihood_field
    update_min_d: 0.05
    update_min_a: 0.2
    odom_frame_id: odom
    base_frame_id: base_link
    global_frame_id: map
    scan_topic: scan
    set_initial_pose: false
