<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="lunabot">
  <xacro:include filename="materials.xacro"/>
  <xacro:property name="base_radius" value="0.25"/>
  <xacro:property name="base_height" value="0.12"/>
  <xacro:property name="wheel_radius" value="0.08"/>
  <xacro:property name="wheel_thickness" value="0.03"/>

  <link name="base_link">
    <visual>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}"/>
      </geometry>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <material name="gray"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}"/>
      </geometry>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="15.0"/>
      <origin xyz="0 0 ${base_height/2}"/>
      <inertia ixx="0.6" ixy="0.0" ixz="0.0" iyy="0.6" iyz="0.0" izz="0.6"/>
    </inertial>
  </link>

  <link name="base_footprint"/>
  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 0"/>
  </joint>

  <xacro:macro name="wheel" params="name x y">
    <link name="${name}">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <material name="black"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      </collision>
      <inertial>
        <mass value="0.5"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
      </inertial>
    </link>
    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}"/>
      <origin xyz="${x} ${y} ${wheel_radius}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:wheel name="wheel_fl" x="${ base_radius - 0.05 }" y="${ base_radius - 0.05 }"/>
  <xacro:wheel name="wheel_fr" x="${ base_radius - 0.05 }" y="${ -base_radius + 0.05 }"/>
  <xacro:wheel name="wheel_rl" x="${ -base_radius + 0.05 }" y="${ base_radius - 0.05 }"/>
  <xacro:wheel name="wheel_rr" x="${ -base_radius + 0.05 }" y="${ -base_radius + 0.05 }"/>

  <link name="lidar_link">
    <visual>
      <geometry>
        <cylinder radius="0.035" length="0.06"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <material name="blue"/>
    </visual>
  </link>
  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0.0 0.0 ${base_height + 0.05}" rpy="0 0 0"/>
  </joint>

  <link name="camera_link">
    <visual>
      <geometry>
        <box size="0.05 0.05 0.03"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>
  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="0.12 0.0 ${base_height + 0.02}" rpy="0 0 0"/>
  </joint>

  <link name="imu_link"/>
  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 ${base_height/2}"/>
  </joint>

  <!-- Gazebo diff-drive plugin to drive via /cmd_vel and publish /odom -->
  <gazebo>
    <plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">
      <ros>
        <namespace>/</namespace>
        <remapping>cmd_vel:=cmd_vel</remapping>
        <remapping>odom:=odom</remapping>
      </ros>
      <update_rate>50</update_rate>
      <left_joint>wheel_fl_joint</left_joint>
      <left_joint>wheel_rl_joint</left_joint>
      <right_joint>wheel_fr_joint</right_joint>
      <right_joint>wheel_rr_joint</right_joint>
      <wheel_separation>${2*base_radius - 0.1}</wheel_separation>
      <wheel_diameter>${2*wheel_radius}</wheel_diameter>
      <publish_tf>true</publish_tf>
      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_footprint</robot_base_frame>
      <cmd_vel_topic>cmd_vel</cmd_vel_topic>
      <odom_topic>odom</odom_topic>
    </plugin>
  </gazebo>

</robot>
